name: fmbox
description: 蜂蜜影音 - 全平台影音软件
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
